export const RESPONSE_CODE = {
  SUCCESS: 'SUCCESS', // 200
  CREATED: 'CREATED', // 201
  NO_CONTENT: 'NO_CONTENT', // 204
  BAD_REQUEST: 'BAD_REQUEST', // 400
  UNAUTHORIZED: 'UNAUTHORIZED', // 401
  FORBIDDEN: 'FORBIDDEN', // 403
  NOT_FOUND: 'NOT_FOUND', // 404
  CONFLICT: 'CONFLICT', // 409
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR', // 500
};
