export const MESSAGE_CODE = {
  // ===== 공통 메시지 =====
  SUCCESS: '요청이 성공적으로 처리되었습니다.',
  ERROR: '서버 오류가 발생했습니다. 잠시 후 다시 시도해주세요.',
  UNAUTHORIZED: '권한이 없습니다.',
  FORBIDDEN: '접근이 금지되었습니다.',
  PERMISSION_DENIED: '관리자만 접근할 수 있습니다.',
  NOT_FOUND: '요청한 리소스를 찾을 수 없습니다.',
  INVALID_REQUEST: '잘못된 요청입니다.',
  ALREADY_EXISTS: '이미 존재하는 항목입니다.',
  DELETED: '성공적으로 삭제되었습니다.',
  INTERNAL_SERVER_ERROR: '서버 내부 오류가 발생했습니다.',

  // ===== 인증 관련 메시지 =====
  // 성공 메시지
  SIGN_UP_SUCCESS: '회원가입이 완료되었습니다.',
  SIGN_IN_SUCCESS: '로그인되었습니다.',
  SIGN_OUT_SUCCESS: '로그아웃되었습니다.',
  FORGOT_PASSWORD_SUCCESS: '비밀번호 재설정 링크가 이메일로 전송되었습니다.',
  PASSWORD_CHANGE_SUCCESS: '비밀번호가 변경되었습니다.',
  WITHDRAW_SUCCESS: '회원탈퇴가 완료되었습니다.',
  FORGOT_PASSWORD_EMAIL_SENT: '비밀번호 재설정 이메일을 발송했습니다. 5분 안에 확인해주세요.',
  NEW_PASSWORD_SET: '새 비밀번호가 성공적으로 설정되었습니다.',
  TOKEN_REFRESH_SUCCESS: '토큰이 성공적으로 갱신되었습니다.',
  SESSION_GET_SUCCESS: '세션 정보를 조회했습니다.',

  // 에러 메시지
  SIGN_UP_ERROR: '회원가입에 실패했습니다.',
  SIGN_IN_ERROR: '로그인에 실패했습니다.',
  SIGN_OUT_ERROR: '로그아웃에 실패했습니다.',
  WITHDRAW_ERROR: '회원탈퇴에 실패했습니다.',
  FORGOT_PASSWORD_ERROR: '비밀번호 재설정 요청에 실패했습니다.',
  PASSWORD_CHANGE_ERROR: '비밀번호 변경에 실패했습니다.',
  EMAIL_IN_USE: '이미 등록된 이메일입니다.',
  INVALID_CREDENTIALS: '이메일 또는 비밀번호가 올바르지 않습니다.',
  SESSION_EXPIRED: '세션이 만료되었습니다. 다시 로그인해주세요.',
  AUTH_ALREADY_EXISTS: '이미 존재하는 계정입니다.',
  AUTH_NOT_FOUND: '계정을 찾을 수 없습니다.',
  INVALID_INPUT: '이메일, 사용자명, 비밀번호는 필수 입력 항목입니다.',
  RESET_TOKEN_AND_PASSWORD_REQUIRED: '리셋 토큰과 새 비밀번호가 필요합니다.',
  INVALID_TOKEN: '유효하지 않은 토큰입니다.',
  INVALID_OR_EXPIRED_RESET_TOKEN: '유효하지 않거나 만료된 리셋 토큰입니다.',
  REFRESH_TOKEN_NOT_FOUND: '리프레시 토큰을 찾을 수 없습니다.',
  INVALID_REFRESH_TOKEN: '유효하지 않은 리프레시 토큰입니다.',
  SESSION_NOT_FOUND: '세션 정보를 찾을 수 없습니다.',

  // ===== 사용자 관련 메시지 =====
  // 성공 메시지
  USER_CREATE_SUCCESS: '사용자가 생성되었습니다.',
  USER_UPDATE_SUCCESS: '사용자 정보가 수정되었습니다.',
  USER_PASSWORD_CHANGE_SUCCESS: '비밀번호가 변경되었습니다.',
  USER_IMAGE_CHANGE_SUCCESS: '프로필 이미지가 변경되었습니다.',
  USER_SEARCH_SUCCESS: '사용자 검색을 완료했습니다.',
  USER_FETCH_SUCCESS: '사용자 정보를 조회했습니다.',
  USER_DELETE_SUCCESS: '사용자가 삭제되었습니다.',
  USER_PROFILE_UPDATED: '프로필이 성공적으로 수정되었습니다.',

  // 에러 메시지
  USER_CREATE_ERROR: '사용자 생성에 실패했습니다.',
  USER_UPDATE_ERROR: '사용자 정보 수정에 실패했습니다.',
  USER_PASSWORD_CHANGE_ERROR: '비밀번호 변경에 실패했습니다.',
  USER_IMAGE_CHANGE_ERROR: '프로필 이미지 변경에 실패했습니다.',
  USER_SEARCH_ERROR: '사용자 검색에 실패했습니다.',
  USER_FETCH_ERROR: '사용자 정보 조회에 실패했습니다.',
  USER_INFO_NOT_FOUND: '사용자 정보를 찾을 수 없습니다.',
  USER_DELETE_ERROR: '사용자 삭제에 실패했습니다.',
  USER_EMAIL_EXISTS: '이미 사용 중인 이메일입니다.',
  USER_NAME_EXISTS: '이미 존재하는 이름입니다.',
  USER_NOT_FOUND: '사용자를 찾을 수 없습니다.',
  USER_PROFILE_UPDATE_FAILED: '프로필 업데이트에 실패했습니다.',
  USER_PROFILE_VALIDATION_FAILED: '프로필 정보가 올바르지 않습니다.',
  USER_PROFILE_DATA_REQUIRED: '필수 프로필 정보가 누락되었습니다.',
  USER_PROFILE_EMAIL_INVALID: '올바른 이메일 형식이 아닙니다.',
  USER_PROFILE_NAME_REQUIRED: '이름은 필수 입력 항목입니다.',
  USER_PROFILE_NAME_TOO_LONG: '이름은 50자를 초과할 수 없습니다.',
  USER_PROFILE_BIO_TOO_LONG: '자기소개는 500자를 초과할 수 없습니다.',
  USER_PROFILE_IMAGE_INVALID: '올바른 이미지 파일이 아닙니다.',

  // ===== 프로필 관련 메시지 =====
  // 조회 관련
  PROFILE_GET_SUCCESS: '프로필 정보를 조회했습니다.',
  PROFILE_GET_BY_EMAIL_SUCCESS: '이메일로 프로필을 조회했습니다.',
  PROFILE_LIST_SUCCESS: '프로필 목록을 조회했습니다.',
  PROFILE_NOT_FOUND: '해당 프로필을 찾을 수 없습니다.',

  // 생성/수정 관련
  PROFILE_CREATE_SUCCESS: '프로필이 생성되었습니다.',
  PROFILE_UPDATE_SUCCESS: '프로필 정보가 수정되었습니다.',

  // 삭제 관련
  PROFILE_DELETE_SUCCESS: '프로필이 삭제되었습니다.',
  PROFILE_DELETE_MULTIPLE_SUCCESS: '선택한 프로필들이 삭제되었습니다.',

  // 중복 체크 관련
  PROFILE_EMAIL_EXISTS: '이미 사용 중인 이메일입니다.',
  PROFILE_USERNAME_EXISTS: '이미 존재하는 사용자명입니다.',

  // 비밀번호 관련
  PROFILE_PASSWORD_CHANGE_SUCCESS: '비밀번호가 변경되었습니다.',
  PROFILE_INVALID_PASSWORD: '현재 비밀번호가 올바르지 않습니다.',

  // 이미지 관련
  PROFILE_IMAGE_CHANGE_SUCCESS: '프로필 이미지가 변경되었습니다.',

  // 에러 메시지
  PROFILE_GET_ERROR: '프로필 정보 조회에 실패했습니다.',
  PROFILE_GET_BY_EMAIL_ERROR: '이메일로 프로필 조회에 실패했습니다.',
  PROFILE_SEARCH_ERROR: '프로필 목록 조회에 실패했습니다.',
  PROFILE_CREATE_ERROR: '프로필 생성에 실패했습니다.',
  PROFILE_UPDATE_ERROR: '프로필 정보 수정에 실패했습니다.',
  PROFILE_DELETE_ERROR: '프로필 삭제에 실패했습니다.',
  PROFILE_DELETE_MULTIPLE_ERROR: '다중 프로필 삭제에 실패했습니다.',
  PROFILE_PASSWORD_CHANGE_ERROR: '비밀번호 변경에 실패했습니다.',
  PROFILE_IMAGE_CHANGE_ERROR: '프로필 이미지 변경에 실패했습니다.',

  // ===== 관리자 관련 메시지 =====
  // 성공 메시지
  ADMIN_SIGN_UP_SUCCESS: '관리자 계정이 성공적으로 생성되었습니다.',
  ADMIN_SIGN_IN_SUCCESS: '관리자로 로그인되었습니다.',
  ADMIN_SIGN_OUT_SUCCESS: '관리자 로그아웃되었습니다.',
  ADMIN_PASSWORD_CHANGE_SUCCESS: '관리자 비밀번호가 성공적으로 변경되었습니다.',
  ADMIN_PROFILE_UPDATE_SUCCESS: '관리자 프로필이 성공적으로 업데이트되었습니다.',
  ADMIN_SEARCH_SUCCESS: '관리자 검색을 완료했습니다.',
  ADMIN_FETCH_SUCCESS: '관리자 정보를 성공적으로 조회했습니다.',
  ADMIN_DELETE_SUCCESS: '관리자 계정이 성공적으로 삭제되었습니다.',
  ADMIN_WITHDRAW_SUCCESS: '관리자 계정이 성공적으로 탈퇴되었습니다.',

  // 관리자 태그 관련 성공 메시지
  ADMIN_TAG_CREATE_SUCCESS: '태그가 생성되었습니다.',
  ADMIN_TAG_MULTIPLE_CREATE_SUCCESS: '다수 태그가 생성되었습니다.',
  ADMIN_TAG_UPDATE_SUCCESS: '태그가 수정되었습니다.',
  ADMIN_TAG_MULTIPLE_UPDATE_SUCCESS: '다수 태그가 수정되었습니다.',
  ADMIN_TAG_DELETE_SUCCESS: '태그가 삭제되었습니다.',
  ADMIN_TAG_MULTIPLE_DELETE_SUCCESS: '다수 태그가 삭제되었습니다.',
  ADMIN_TAG_SEARCH_SUCCESS: '태그 검색을 완료했습니다.',
  ADMIN_TAG_MAPPING_SEARCH_SUCCESS: '태그 매핑 검색을 완료했습니다.',
  ADMIN_TAG_MAPPING_CREATE_SUCCESS: '태그 매핑이 생성되었습니다.',
  ADMIN_TAG_MAPPING_DELETE_SUCCESS: '태그 매핑이 삭제되었습니다.',

  // 에러 메시지
  ADMIN_SIGN_UP_ERROR: '관리자 계정 생성에 실패했습니다.',
  ADMIN_SIGN_IN_ERROR: '관리자 로그인에 실패했습니다.',
  ADMIN_SIGN_OUT_ERROR: '관리자 로그아웃에 실패했습니다.',
  ADMIN_PASSWORD_CHANGE_ERROR: '관리자 비밀번호 변경에 실패했습니다.',
  ADMIN_PROFILE_UPDATE_ERROR: '관리자 프로필 업데이트에 실패했습니다.',
  ADMIN_SEARCH_ERROR: '관리자 검색에 실패했습니다.',
  ADMIN_FETCH_ERROR: '관리자 정보 조회에 실패했습니다.',
  ADMIN_DELETE_ERROR: '관리자 계정 삭제에 실패했습니다.',
  ADMIN_WITHDRAW_ERROR: '관리자 계정 탈퇴에 실패했습니다.',
  ADMIN_EMAIL_EXISTS: '이미 사용 중인 관리자 이메일입니다.',
  ADMIN_NAME_EXISTS: '이미 사용 중인 관리자명입니다.',
  ADMIN_NOT_FOUND: '관리자를 찾을 수 없습니다.',
  ADMIN_INVALID_CREDENTIALS: '관리자 이메일 또는 비밀번호가 올바르지 않습니다.',
  ADMIN_SESSION_EXPIRED: '관리자 세션이 만료되었습니다. 다시 로그인해주세요.',
  ADMIN_UNAUTHORIZED: '관리자 권한이 필요합니다.',
  ADMIN_FORBIDDEN: '관리자만 접근할 수 있는 기능입니다.',
  ADMIN_INVALID_INPUT: '관리자 이메일, 사용자명, 비밀번호는 필수 입력 항목입니다.',
  ADMIN_PROFILE_UPDATE_FAILED: '관리자 프로필 업데이트에 실패했습니다.',
  ADMIN_PROFILE_VALIDATION_FAILED: '관리자 프로필 정보가 유효하지 않습니다.',
  ADMIN_PROFILE_DATA_REQUIRED: '관리자 프로필 데이터가 필요합니다.',
  ADMIN_PROFILE_EMAIL_INVALID: '유효하지 않은 관리자 이메일 형식입니다.',
  ADMIN_PROFILE_NAME_REQUIRED: '관리자명은 필수 입력 항목입니다.',
  ADMIN_PROFILE_NAME_TOO_LONG: '관리자명이 너무 깁니다. (최대 50자)',
  ADMIN_PROFILE_BIO_TOO_LONG: '관리자 소개가 너무 깁니다. (최대 500자)',
  ADMIN_PROFILE_IMAGE_INVALID: '유효하지 않은 관리자 프로필 이미지입니다.',
  ADMIN_PASSWORD_VALIDATION_FAILED: '관리자 비밀번호가 유효하지 않습니다.',
  ADMIN_PASSWORD_MISMATCH: '새 비밀번호와 확인 비밀번호가 일치하지 않습니다.',
  ADMIN_CURRENT_PASSWORD_INCORRECT: '현재 비밀번호가 올바르지 않습니다.',

  // 관리자 태그 관련 에러 메시지
  ADMIN_TAG_CREATE_ERROR: '태그 생성에 실패했습니다.',
  ADMIN_TAG_MULTIPLE_CREATE_ERROR: '다수 태그 생성에 실패했습니다.',
  ADMIN_TAG_UPDATE_ERROR: '태그 수정에 실패했습니다.',
  ADMIN_TAG_MULTIPLE_UPDATE_ERROR: '다수 태그 수정에 실패했습니다.',
  ADMIN_TAG_DELETE_ERROR: '태그 삭제에 실패했습니다.',
  ADMIN_TAG_MULTIPLE_DELETE_ERROR: '다수 태그 삭제에 실패했습니다.',
  ADMIN_TAG_SEARCH_ERROR: '태그 검색에 실패했습니다.',
  ADMIN_TAG_NOT_FOUND: '태그를 찾을 수 없습니다.',
  ADMIN_TAG_ALREADY_EXISTS: '이미 존재하는 태그입니다.',
  ADMIN_TAG_NAME_IN_USE: '이미 사용 중인 태그 이름입니다.',
  ADMIN_TAG_NAME_REQUIRED: '태그 이름은 필수 입력 항목입니다.',
  ADMIN_TAG_SLUG_DUPLICATE: '이미 존재하는 태그 슬러그입니다.',
  ADMIN_TAG_MAPPING_ALREADY_EXISTS: '이미 태그 매핑이 존재합니다.',
  ADMIN_TAG_MAPPING_SEARCH_ERROR: '태그 매핑 검색에 실패했습니다.',
  ADMIN_TAG_MAPPING_CREATE_ERROR: '태그 매핑 생성에 실패했습니다.',
  ADMIN_TAG_MAPPING_DELETE_ERROR: '태그 매핑 삭제에 실패했습니다.',

  // ===== 카테고리 관련 메시지 =====
  // 성공 메시지
  CATEGORY_SEARCH_SUCCESS: '카테고리 목록을 조회했습니다.',
  CATEGORY_GET_SUCCESS: '카테고리 정보를 조회했습니다.',
  CATEGORY_GET_BY_NAME_SUCCESS: '카테고리명으로 카테고리를 조회했습니다.',

  // 에러 메시지
  CATEGORY_SEARCH_ERROR: '카테고리 목록 조회에 실패했습니다.',
  CATEGORY_GET_ERROR: '카테고리 정보 조회에 실패했습니다.',
  CATEGORY_GET_BY_NAME_ERROR: '카테고리명으로 카테고리 조회에 실패했습니다.',
  CATEGORY_NOT_FOUND: '카테고리를 찾을 수 없습니다.',
  CATEGORY_NAME_NOT_FOUND: '해당 이름의 카테고리를 찾을 수 없습니다.',

  // ===== 태그 관련 메시지 =====
  // 성공 메시지
  TAG_SEARCH_SUCCESS: '태그 목록을 조회했습니다.',
  TAG_GET_SUCCESS: '태그 정보를 조회했습니다.',
  TAG_GET_BY_NAME_SUCCESS: '태그명으로 태그를 조회했습니다.',

  // 에러 메시지
  TAG_SEARCH_ERROR: '태그 목록 조회에 실패했습니다.',
  TAG_GET_ERROR: '태그 정보 조회에 실패했습니다.',
  TAG_GET_BY_NAME_ERROR: '태그명으로 태그 조회에 실패했습니다.',
  TAG_NOT_FOUND: '태그를 찾을 수 없습니다.',
  TAG_NAME_NOT_FOUND: '해당 이름의 태그를 찾을 수 없습니다.',

  // ===== 관리자 카테고리 관련 메시지 =====
  // 성공 메시지
  ADMIN_CATEGORY_SEARCH_SUCCESS: '관리자 카테고리 목록을 조회했습니다.',
  ADMIN_CATEGORY_GET_SUCCESS: '관리자 카테고리 정보를 조회했습니다.',
  ADMIN_CATEGORY_GET_BY_NAME_SUCCESS: '관리자 카테고리명으로 카테고리를 조회했습니다.',
  ADMIN_CATEGORY_CREATE_SUCCESS: '카테고리가 생성되었습니다.',
  ADMIN_CATEGORY_MULTIPLE_CREATE_SUCCESS: '다수 카테고리가 생성되었습니다.',
  ADMIN_CATEGORY_UPDATE_SUCCESS: '카테고리가 수정되었습니다.',
  ADMIN_CATEGORY_MULTIPLE_UPDATE_SUCCESS: '다수 카테고리가 수정되었습니다.',
  ADMIN_CATEGORY_DELETE_SUCCESS: '카테고리가 삭제되었습니다.',
  ADMIN_CATEGORY_MULTIPLE_DELETE_SUCCESS: '다수 카테고리가 삭제되었습니다.',

  // 에러 메시지
  ADMIN_CATEGORY_SEARCH_ERROR: '관리자 카테고리 목록 조회에 실패했습니다.',
  ADMIN_CATEGORY_GET_ERROR: '관리자 카테고리 정보 조회에 실패했습니다.',
  ADMIN_CATEGORY_GET_BY_NAME_ERROR: '관리자 카테고리명으로 카테고리 조회에 실패했습니다.',
  ADMIN_CATEGORY_CREATE_ERROR: '카테고리 생성에 실패했습니다.',
  ADMIN_CATEGORY_MULTIPLE_CREATE_ERROR: '다수 카테고리 생성에 실패했습니다.',
  ADMIN_CATEGORY_UPDATE_ERROR: '카테고리 수정에 실패했습니다.',
  ADMIN_CATEGORY_MULTIPLE_UPDATE_ERROR: '다수 카테고리 수정에 실패했습니다.',
  ADMIN_CATEGORY_DELETE_ERROR: '카테고리 삭제에 실패했습니다.',
  ADMIN_CATEGORY_MULTIPLE_DELETE_ERROR: '다수 카테고리 삭제에 실패했습니다.',
  ADMIN_CATEGORY_NOT_FOUND: '관리할 카테고리를 찾을 수 없습니다.',
  ADMIN_CATEGORY_NAME_NOT_FOUND: '해당 이름의 관리자 카테고리를 찾을 수 없습니다.',
  ADMIN_CATEGORY_NAME_IN_USE: '이미 사용 중인 카테고리 이름입니다.',
  ADMIN_CATEGORY_NAME_REQUIRED: '카테고리 이름은 필수 입력 항목입니다.',

  // ===== 구독 관련 메시지 =====
  // 성공 메시지
  SUBSCRIBE_FETCH_SUCCESS: '구독 설정을 조회했습니다.',
  SUBSCRIBE_UPDATE_SUCCESS: '구독 설정이 수정되었습니다.',
  SUBSCRIBE_CREATE_SUCCESS: '구독 설정이 생성되었습니다.',
  SUBSCRIBE_DELETE_SUCCESS: '구독 설정이 삭제되었습니다.',
  SUBSCRIBE_SEARCH_SUCCESS: '구독 설정 검색을 완료했습니다.',
  SUBSCRIBE_MULTIPLE_CREATE_SUCCESS: '다수 구독 설정이 생성되었습니다.',
  SUBSCRIBE_MULTIPLE_UPDATE_SUCCESS: '다수 구독 설정이 수정되었습니다.',
  SUBSCRIBE_MULTIPLE_DELETE_SUCCESS: '다수 구독 설정이 삭제되었습니다.',

  // 관리자 구독 관련 성공 메시지
  ADMIN_SUBSCRIBE_SEARCH_SUCCESS: '전체 사용자 구독 설정 검색을 완료했습니다.',
  ADMIN_SUBSCRIBE_CREATE_SUCCESS: '사용자 구독 설정이 생성되었습니다.',
  ADMIN_SUBSCRIBE_MULTIPLE_CREATE_SUCCESS: '다수 사용자 구독 설정이 생성되었습니다.',
  ADMIN_SUBSCRIBE_MULTIPLE_UPDATE_SUCCESS: '다수 사용자 구독 설정이 수정되었습니다.',
  ADMIN_SUBSCRIBE_DELETE_SUCCESS: '사용자 구독 설정이 삭제되었습니다.',
  ADMIN_SUBSCRIBE_MULTIPLE_DELETE_SUCCESS: '다수 사용자 구독 설정이 삭제되었습니다.',

  // 카테고리 구독 관련
  CATEGORY_SUBSCRIBE_CREATE_SUCCESS: '카테고리 구독이 설정되었습니다.',
  CATEGORY_SUBSCRIBE_UPDATE_SUCCESS: '카테고리 구독이 수정되었습니다.',
  CATEGORY_SUBSCRIBE_DELETE_SUCCESS: '카테고리 구독이 해제되었습니다.',
  CATEGORY_SUBSCRIBE_SEARCH_SUCCESS: '카테고리 구독 검색을 완료했습니다.',
  CATEGORY_SUBSCRIBE_MULTIPLE_CREATE_SUCCESS: '다수 카테고리 구독이 설정되었습니다.',
  CATEGORY_SUBSCRIBE_MULTIPLE_UPDATE_SUCCESS: '다수 카테고리 구독이 수정되었습니다.',
  CATEGORY_SUBSCRIBE_MULTIPLE_DELETE_SUCCESS: '다수 카테고리 구독이 해제되었습니다.',

  // 관리자 카테고리 구독 관련 성공 메시지
  ADMIN_CATEGORY_SUBSCRIBE_SEARCH_SUCCESS: '관리자 카테고리 구독 검색을 완료했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_BY_CATEGORY_SUCCESS: '카테고리별 구독자 목록을 조회했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_CREATE_SUCCESS: '관리자가 카테고리 구독을 생성했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_MULTIPLE_CREATE_SUCCESS: '관리자가 다수 카테고리 구독을 생성했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_UPDATE_SUCCESS: '관리자가 카테고리 구독을 수정했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_MULTIPLE_UPDATE_SUCCESS: '관리자가 다수 카테고리 구독을 수정했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_DELETE_SUCCESS: '관리자가 카테고리 구독을 삭제했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_MULTIPLE_DELETE_SUCCESS: '관리자가 다수 카테고리 구독을 삭제했습니다.',

  // 태그 구독 관련
  TAG_SUBSCRIBE_CREATE_SUCCESS: '태그 구독이 설정되었습니다.',
  TAG_SUBSCRIBE_UPDATE_SUCCESS: '태그 구독이 수정되었습니다.',
  TAG_SUBSCRIBE_DELETE_SUCCESS: '태그 구독이 해제되었습니다.',
  TAG_SUBSCRIBE_SEARCH_SUCCESS: '태그 구독 검색을 완료했습니다.',
  TAG_SUBSCRIBE_MULTIPLE_CREATE_SUCCESS: '다수 태그 구독이 설정되었습니다.',
  TAG_SUBSCRIBE_MULTIPLE_UPDATE_SUCCESS: '다수 태그 구독이 수정되었습니다.',
  TAG_SUBSCRIBE_MULTIPLE_DELETE_SUCCESS: '다수 태그 구독이 해제되었습니다.',

  // 관리자 태그 구독 관련 성공 메시지
  ADMIN_TAG_SUBSCRIBE_SEARCH_SUCCESS: '관리자 태그 구독 검색을 완료했습니다.',
  ADMIN_TAG_SUBSCRIBE_BY_TAG_SUCCESS: '태그별 구독자 목록을 조회했습니다.',
  ADMIN_TAG_SUBSCRIBE_CREATE_SUCCESS: '관리자가 태그 구독을 생성했습니다.',
  ADMIN_TAG_SUBSCRIBE_MULTIPLE_CREATE_SUCCESS: '관리자가 다수 태그 구독을 생성했습니다.',
  ADMIN_TAG_SUBSCRIBE_UPDATE_SUCCESS: '관리자가 태그 구독을 수정했습니다.',
  ADMIN_TAG_SUBSCRIBE_MULTIPLE_UPDATE_SUCCESS: '관리자가 다수 태그 구독을 수정했습니다.',
  ADMIN_TAG_SUBSCRIBE_DELETE_SUCCESS: '관리자가 태그 구독을 삭제했습니다.',
  ADMIN_TAG_SUBSCRIBE_MULTIPLE_DELETE_SUCCESS: '관리자가 다수 태그 구독을 삭제했습니다.',

  // 에러 메시지
  SUBSCRIBE_FETCH_ERROR: '구독 설정 조회에 실패했습니다.',
  SUBSCRIBE_UPDATE_ERROR: '구독 설정 수정에 실패했습니다.',
  SUBSCRIBE_CREATE_ERROR: '구독 설정 생성에 실패했습니다.',
  SUBSCRIBE_DELETE_ERROR: '구독 설정 삭제에 실패했습니다.',
  SUBSCRIBE_NOT_FOUND: '구독 설정을 찾을 수 없습니다.',
  SUBSCRIBE_SEARCH_ERROR: '구독 검색에 실패했습니다.',
  SUBSCRIBE_MULTIPLE_CREATE_ERROR: '다수 구독 설정 생성에 실패했습니다.',
  SUBSCRIBE_MULTIPLE_UPDATE_ERROR: '다수 구독 설정 수정에 실패했습니다.',
  SUBSCRIBE_MULTIPLE_DELETE_ERROR: '다수 구독 설정 삭제에 실패했습니다.',

  // 관리자 구독 관련 에러 메시지
  ADMIN_SUBSCRIBE_SEARCH_ERROR: '전체 사용자 구독 설정 검색에 실패했습니다.',
  ADMIN_SUBSCRIBE_CREATE_ERROR: '사용자 구독 설정 생성에 실패했습니다.',
  ADMIN_SUBSCRIBE_MULTIPLE_CREATE_ERROR: '다수 사용자 구독 설정 생성에 실패했습니다.',
  ADMIN_SUBSCRIBE_MULTIPLE_UPDATE_ERROR: '다수 사용자 구독 설정 수정에 실패했습니다.',
  ADMIN_SUBSCRIBE_DELETE_ERROR: '사용자 구독 설정 삭제에 실패했습니다.',
  ADMIN_SUBSCRIBE_MULTIPLE_DELETE_ERROR: '다수 사용자 구독 설정 삭제에 실패했습니다.',
  ADMIN_SUBSCRIBE_ALREADY_EXISTS: '이미 구독 설정이 존재합니다.',
  ADMIN_SUBSCRIBE_ALREADY_DELETED: '이미 삭제된 구독 설정입니다.',
  ADMIN_SUBSCRIBE_INVALID_USER_LIST: '유효하지 않은 사용자 목록입니다.',

  // 카테고리 구독 에러
  CATEGORY_SUBSCRIBE_CREATE_ERROR: '카테고리 구독 설정에 실패했습니다.',
  CATEGORY_SUBSCRIBE_UPDATE_ERROR: '카테고리 구독 수정에 실패했습니다.',
  CATEGORY_SUBSCRIBE_DELETE_ERROR: '카테고리 구독 해제에 실패했습니다.',
  CATEGORY_SUBSCRIBE_NOT_FOUND: '카테고리 구독을 찾을 수 없습니다.',
  CATEGORY_SUBSCRIBE_SEARCH_ERROR: '카테고리 구독 검색에 실패했습니다.',
  CATEGORY_SUBSCRIBE_MULTIPLE_CREATE_ERROR: '다수 카테고리 구독 설정에 실패했습니다.',
  CATEGORY_SUBSCRIBE_MULTIPLE_UPDATE_ERROR: '다수 카테고리 구독 수정에 실패했습니다.',
  CATEGORY_SUBSCRIBE_MULTIPLE_DELETE_ERROR: '다수 카테고리 구독 해제에 실패했습니다.',
  CATEGORY_SUBSCRIBE_ALREADY_EXISTS: '이미 구독 중인 카테고리입니다.',

  // 관리자 카테고리 구독 관련 에러 메시지
  ADMIN_CATEGORY_SUBSCRIBE_SEARCH_ERROR: '관리자 카테고리 구독 검색에 실패했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_BY_CATEGORY_ERROR: '카테고리별 구독자 조회에 실패했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_CREATE_ERROR: '관리자 카테고리 구독 생성에 실패했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_MULTIPLE_CREATE_ERROR: '관리자 다수 카테고리 구독 생성에 실패했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_UPDATE_ERROR: '관리자 카테고리 구독 수정에 실패했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_MULTIPLE_UPDATE_ERROR: '관리자 다수 카테고리 구독 수정에 실패했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_DELETE_ERROR: '관리자 카테고리 구독 삭제에 실패했습니다.',
  ADMIN_CATEGORY_SUBSCRIBE_MULTIPLE_DELETE_ERROR: '관리자 다수 카테고리 구독 삭제에 실패했습니다.',

  // 태그 구독 에러
  TAG_SUBSCRIBE_CREATE_ERROR: '태그 구독 설정에 실패했습니다.',
  TAG_SUBSCRIBE_UPDATE_ERROR: '태그 구독 수정에 실패했습니다.',
  TAG_SUBSCRIBE_DELETE_ERROR: '태그 구독 해제에 실패했습니다.',
  TAG_SUBSCRIBE_NOT_FOUND: '태그 구독을 찾을 수 없습니다.',
  TAG_SUBSCRIBE_SEARCH_ERROR: '태그 구독 검색에 실패했습니다.',
  TAG_SUBSCRIBE_MULTIPLE_CREATE_ERROR: '다수 태그 구독 설정에 실패했습니다.',
  TAG_SUBSCRIBE_MULTIPLE_UPDATE_ERROR: '다수 태그 구독 수정에 실패했습니다.',
  TAG_SUBSCRIBE_MULTIPLE_DELETE_ERROR: '다수 태그 구독 해제에 실패했습니다.',
  TAG_SUBSCRIBE_ALREADY_EXISTS: '이미 구독 중인 태그입니다.',

  // 관리자 태그 구독 관련 에러 메시지
  ADMIN_TAG_SUBSCRIBE_SEARCH_ERROR: '관리자 태그 구독 검색에 실패했습니다.',
  ADMIN_TAG_SUBSCRIBE_BY_TAG_ERROR: '태그별 구독자 조회에 실패했습니다.',
  ADMIN_TAG_SUBSCRIBE_CREATE_ERROR: '관리자 태그 구독 생성에 실패했습니다.',
  ADMIN_TAG_SUBSCRIBE_MULTIPLE_CREATE_ERROR: '관리자 다수 태그 구독 생성에 실패했습니다.',
  ADMIN_TAG_SUBSCRIBE_UPDATE_ERROR: '관리자 태그 구독 수정에 실패했습니다.',
  ADMIN_TAG_SUBSCRIBE_MULTIPLE_UPDATE_ERROR: '관리자 다수 태그 구독 수정에 실패했습니다.',
  ADMIN_TAG_SUBSCRIBE_DELETE_ERROR: '관리자 태그 구독 삭제에 실패했습니다.',
  ADMIN_TAG_SUBSCRIBE_MULTIPLE_DELETE_ERROR: '관리자 다수 태그 구독 삭제에 실패했습니다.',

  // 구독 설정 관련
  SUBSCRIBE_EMAIL_NOTIFICATION_ERROR: '이메일 알림 설정에 실패했습니다.',
  SUBSCRIBE_PUSH_NOTIFICATION_ERROR: '푸시 알림 설정에 실패했습니다.',
  SUBSCRIBE_CATEGORY_LIST_INVALID: '구독 카테고리 목록이 올바르지 않습니다.',
  SUBSCRIBE_TAG_LIST_INVALID: '구독 태그 목록이 올바르지 않습니다.',
  SUBSCRIBE_ALREADY_EXISTS: '이미 구독 중인 항목입니다.',
  SUBSCRIBE_DUPLICATE_CATEGORY: '중복된 카테고리 구독입니다.',
  SUBSCRIBE_DUPLICATE_TAG: '중복된 태그 구독입니다.',

  // ===== 게시글 관련 메시지 =====
  // 일반 사용자 성공 메시지
  POST_SEARCH_SUCCESS: '게시글 목록을 조회했습니다.',
  POST_GET_SUCCESS: '게시글 정보를 조회했습니다.',
  POST_GET_BY_SLUG_SUCCESS: '게시글을 조회했습니다.',
  POST_GET_BY_TAG_SUCCESS: '태그별 게시글 목록을 조회했습니다.',
  POST_GET_BY_CATEGORY_SUCCESS: '카테고리별 게시글 목록을 조회했습니다.',
  POST_GET_ARCHIVE_SUCCESS: '아카이브 게시글 목록을 조회했습니다.',
  POST_LIKE_SUCCESS: '게시글에 좋아요를 눌렀습니다.',
  POST_LIKE_CANCEL_SUCCESS: '게시글 좋아요를 취소했습니다.',
  POST_BOOKMARK_SUCCESS: '게시글을 북마크했습니다.',
  POST_BOOKMARK_CANCEL_SUCCESS: '게시글 북마크를 취소했습니다.',
  POST_BOOKMARK_CREATE_SUCCESS: '게시글 북마크가 생성되었습니다.',
  POST_BOOKMARK_DELETE_SUCCESS: '게시글 북마크가 삭제되었습니다.',
  POST_BOOKMARK_UPDATE_SUCCESS: '게시글 북마크가 수정되었습니다.',
  POST_BOOKMARK_GET_SUCCESS: '게시글 북마크 정보를 조회했습니다.',
  POST_BOOKMARK_SEARCH_SUCCESS: '북마크한 게시글 검색을 완료했습니다.',
  POST_SHARE_SUCCESS: '게시글을 공유했습니다.',
  POST_VIEW_STATS_SUCCESS: '게시글 조회수 통계를 조회했습니다.',
  POST_SHARE_STATS_SUCCESS: '게시글 공유 통계를 조회했습니다.',
  POST_VIEW_LOG_SUCCESS: '게시글 조회 로그를 기록했습니다.',
  POST_SHARE_LOG_SUCCESS: '게시글 공유 로그를 기록했습니다.',

  // 일반 사용자 에러 메시지
  POST_SEARCH_ERROR: '게시글 목록 조회에 실패했습니다.',
  POST_GET_ERROR: '게시글 정보 조회에 실패했습니다.',
  POST_GET_BY_SLUG_ERROR: '게시글 조회에 실패했습니다.',
  POST_GET_BY_TAG_ERROR: '태그별 게시글 목록 조회에 실패했습니다.',
  POST_GET_BY_CATEGORY_ERROR: '카테고리별 게시글 목록 조회에 실패했습니다.',
  POST_GET_ARCHIVE_ERROR: '아카이브 게시글 목록 조회에 실패했습니다.',
  POST_LIKE_ERROR: '게시글 좋아요 처리에 실패했습니다.',
  POST_BOOKMARK_ERROR: '게시글 북마크 처리에 실패했습니다.',
  POST_BOOKMARK_CREATE_ERROR: '게시글 북마크 생성에 실패했습니다.',
  POST_BOOKMARK_DELETE_ERROR: '게시글 북마크 삭제에 실패했습니다.',
  POST_BOOKMARK_UPDATE_ERROR: '게시글 북마크 수정에 실패했습니다.',
  POST_BOOKMARK_GET_ERROR: '게시글 북마크 정보 조회에 실패했습니다.',
  POST_BOOKMARK_SEARCH_ERROR: '북마크한 게시글 검색에 실패했습니다.',
  POST_SHARE_ERROR: '게시글 공유에 실패했습니다.',
  POST_VIEW_STATS_ERROR: '게시글 조회수 통계 조회에 실패했습니다.',
  POST_SHARE_STATS_ERROR: '게시글 공유 통계 조회에 실패했습니다.',
  POST_NOT_FOUND: '게시글을 찾을 수 없습니다.',
  POST_ALREADY_LIKED: '이미 좋아요를 누른 게시글입니다.',
  POST_ALREADY_BOOKMARKED: '이미 북마크한 게시글입니다.',
  POST_NOT_LIKED: '좋아요를 누르지 않은 게시글입니다.',
  POST_NOT_BOOKMARKED: '북마크하지 않은 게시글입니다.',
  POST_INVALID_SLUG: '유효하지 않은 게시글 슬러그입니다.',
  POST_INVALID_TAG: '유효하지 않은 태그입니다.',
  POST_INVALID_CATEGORY: '유효하지 않은 카테고리입니다.',
  POST_INVALID_ARCHIVE_DATE: '유효하지 않은 아카이브 날짜입니다.',
  POST_VIEW_LOG_ERROR: '게시글 조회 로그 기록에 실패했습니다.',
  POST_SHARE_LOG_ERROR: '게시글 공유 로그 기록에 실패했습니다.',

  // 관리자 성공 메시지
  ADMIN_POST_CREATE_SUCCESS: '게시글이 생성되었습니다.',
  ADMIN_POST_UPDATE_SUCCESS: '게시글 정보가 수정되었습니다.',
  ADMIN_POST_MULTIPLE_UPDATE_SUCCESS: '다수 게시글이 수정되었습니다.',
  ADMIN_POST_DELETE_SUCCESS: '게시글이 삭제되었습니다.',
  ADMIN_POST_MULTIPLE_DELETE_SUCCESS: '다수 게시글이 삭제되었습니다.',
  ADMIN_POST_SEARCH_SUCCESS: '관리자 게시글 검색을 완료했습니다.',
  ADMIN_POST_STATISTICS_SUCCESS: '게시글 통계를 조회했습니다.',
  ADMIN_POST_FEATURE_SUCCESS: '게시글이 추천으로 설정되었습니다.',
  ADMIN_POST_FEATURE_CANCEL_SUCCESS: '게시글 추천이 해제되었습니다.',
  ADMIN_POST_PIN_SUCCESS: '게시글이 고정되었습니다.',
  ADMIN_POST_PIN_CANCEL_SUCCESS: '게시글 고정이 해제되었습니다.',

  // 관리자 에러 메시지
  ADMIN_POST_CREATE_ERROR: '게시글 생성에 실패했습니다.',
  ADMIN_POST_UPDATE_ERROR: '게시글 정보 수정에 실패했습니다.',
  ADMIN_POST_MULTIPLE_UPDATE_ERROR: '다수 게시글 수정에 실패했습니다.',
  ADMIN_POST_DELETE_ERROR: '게시글 삭제에 실패했습니다.',
  ADMIN_POST_MULTIPLE_DELETE_ERROR: '다수 게시글 삭제에 실패했습니다.',
  ADMIN_POST_SEARCH_ERROR: '관리자 게시글 검색에 실패했습니다.',
  ADMIN_POST_STATISTICS_ERROR: '게시글 통계 조회에 실패했습니다.',
  ADMIN_POST_FEATURE_ERROR: '게시글 추천 설정에 실패했습니다.',
  ADMIN_POST_PIN_ERROR: '게시글 고정 설정에 실패했습니다.',
  ADMIN_POST_NOT_FOUND: '관리할 게시글을 찾을 수 없습니다.',
  ADMIN_POST_ALREADY_FEATURED: '이미 추천된 게시글입니다.',
  ADMIN_POST_ALREADY_PINNED: '이미 고정된 게시글입니다.',
  ADMIN_POST_NOT_FEATURED: '추천되지 않은 게시글입니다.',
  ADMIN_POST_NOT_PINNED: '고정되지 않은 게시글입니다.',
  ADMIN_POST_INVALID_STATUS: '유효하지 않은 게시글 상태입니다.',
  ADMIN_POST_INVALID_CATEGORY: '유효하지 않은 카테고리입니다.',
  ADMIN_POST_INVALID_TAG: '유효하지 않은 태그입니다.',
  ADMIN_POST_CONTENT_REQUIRED: '게시글 내용은 필수 입력 항목입니다.',
  ADMIN_POST_TITLE_REQUIRED: '게시글 제목은 필수 입력 항목입니다.',
  ADMIN_POST_TITLE_TOO_LONG: '게시글 제목이 너무 깁니다. (최대 200자)',
  ADMIN_POST_CONTENT_TOO_LONG: '게시글 내용이 너무 깁니다. (최대 10000자)',
  ADMIN_POST_SLUG_INVALID: '유효하지 않은 게시글 슬러그입니다.',
  ADMIN_POST_SLUG_DUPLICATE: '이미 존재하는 게시글 슬러그입니다.',

  // ===== 데이터베이스 관련 메시지 =====
  // 성공/정보 메시지
  DB_CONNECTED: '데이터베이스에 연결되었습니다.',
  DB_DISCONNECTED: '데이터베이스 연결이 종료되었습니다.',

  // 에러 메시지
  DB_CONNECTION_ERROR: '데이터베이스 연결에 실패했습니다.',
  DB_QUERY_ERROR: '데이터베이스 쿼리 실행에 실패했습니다.',
  PRISMA_INIT_ERROR: 'Prisma 초기화에 실패했습니다.',
} as const;
